version: "3.8"

services:
  app:
    build: .
    container_name: blog_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=blog
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - .:/usr/src/app
    networks:
      - blog_network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blog_network

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - blog_network

volumes:
  pgdata:
  mongodata:

networks:
  blog_network:
    driver: bridge
